### ISSUE TITLE
image generatorが落ちている

### ISSUE THREAD

**Issue by MitsukiUsui** [politylink/politylink-tube#34]
2024/4/11以降サムネが表示されなくなっているように見える。
ログを確認したところ、以下のようなエラーが出ていた。

```
INFO:mylib.artifact.image.generator:out/artifact/image/clip/l/12527.jpg already exists
Traceback (most recent call last):
  File "/Users/mitsuki/politylink/politylink-tube/builder/generate_images.py", line 81, in <module>
    main()
  File "/Users/mitsuki/politylink/politylink-tube/builder/generate_images.py", line 65, in main
    response = generator.generate(request)
  File "/Users/mitsuki/politylink/politylink-tube/builder/mylib/artifact/image/generator.py", line 57, in generate
    image = cv2.resize(image, dsize=request.dsize)
cv2.error: OpenCV(4.7.0) /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

**Comment by MitsukiUsui** [comment]
clipId = 12612をスキップすることで一時的に対応。この動画がなぜ処理できないかは要調査。
